---
- hosts: all
  sudo: yes
  tasks:
- name: Ensure NTP (for type synchronisation) is installed.
  yum: name=ntp state=present
- name: Ensure NTP is running.
  service: name=ntpd state started enabled=yes